version: '3.8'
services:
  backend:
    env_file:
      - server/.env
    build:
      context: ./server/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    expose:
      - 8000

  frontend:
    build:
      context: ./client/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:5173:5173"
    expose:
      - 5173
